version: '3.3'
services:
  server:
    build: .
    image: imslavko/image-labeling-tool:latest
    # user: ${CURRENT_UID}
    volumes:
      - d:/project/verification_code/data:/uploads
      - d:/project/verification_code/data/image-labeling-tool/db:/db
    ports:
     - "5000:3000"
